### PR TITLE
Cleanup MTDevice reloading on wakeup

### PR DESCRIPTION
**Pull request by aaronkollasch**
Jitouch must reload its MTDevices when the system wakes from sleep. The old way of doing this is to kill and restart the Jitouch process. While this ensures a full reload, it is inelegant. I've also seen reliability issues that require a manual restart.

This PR adds a `reload()` function to `jitouch/Jitouch/JitouchAppDelegate.m` that reloads the MTDevices and is called upon wake from sleep. Reloading can also be triggered by sending SIGHUP to the Jitouch process, for example with `killall -HUP Jitouch`.

For signal handling examples see:
- https://stackoverflow.com/questions/50225548/trap-sigint-in-cocoa-macos-application
- https://www.mikeash.com/pyblog/friday-qa-2011-04-01-signal-handling.html
- https://fossies.org/linux/HandBrake/macosx/main.m

Automatic reloading on wake has been tested with the built-in trackpad, but it is possible that some Magic Trackpad and Magic Mouse related code (specifically, the [device-added notifications](https://github.com/aaronkollasch/jitouch/blob/ed0c5e11ab2c6c673e3bad38299f39b07188db0c/jitouch/Jitouch/Gesture.m#L2947), [updateDevicesMM](https://github.com/aaronkollasch/jitouch/blob/ed0c5e11ab2c6c673e3bad38299f39b07188db0c/jitouch/Jitouch/Gesture.m#L2541) and [updateDevicesMT](https://github.com/aaronkollasch/jitouch/blob/ed0c5e11ab2c6c673e3bad38299f39b07188db0c/jitouch/Jitouch/Gesture.m#L600)) will need to be reloaded as well (so testing with those devices is needed). However, updateDevicesMM and updateDevicesMT appear unused, the notifications are not essential functionality, and all other parts of MT and MM support should function properly.

### CODE REVIEW

**Comment by smilingpoplar** [comment]
when will this fix ready? jitouch is not working from time to time

**Comment by aaronkollasch** [comment]
It's ready now. I didn't want to include it with the first release since I can't test if it'll affect support for the Magic Trackpad or Magic Mouse. I'll release it soon now that v2.75 is out.

**Comment by smilingpoplar** [comment]
awesome

Aaron Kollasch ***@***.***>于2021年11月27日 周六10:28写道：

**Comment by aaronkollasch** [comment]
New release is [up](https://github.com/aaronkollasch/jitouch/releases/tag/v2.76). Thank you for the comment @smilingpoplar.

**Comment by smilingpoplar** [comment]
@aaronkollasch jitouch not reloading when wakeup from minutes sleeping. 

Where can I find some log?

**Comment by aaronkollasch** [comment]
I've encountered this problem too. After a longer sleep I still have to manually start Jitouch. I think the fix will be using a LaunchAgent to run Jitouch instead of enabling it as a startup item, but I haven't gotten to it yet.

Jitouch doesn't output logs to a file, but LaunchAgents can, so in the meantime, you can try running Jitouch as a LaunchAgent with these steps:

- create `~/Library/LaunchAgents/com.jitouch.Jitouch.plist`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>Jitouch</string>
	<key>ProcessType</key>
	<string>Interactive</string>
	<key>Program</key>
	<string>/PATH/TO/Library/PreferencePanes/Jitouch.prefPane/Contents/Resources/Jitouch.app/Contents/MacOS/Jitouch</string>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardErrorPath</key>
	<string>/Users/USERNAME/Library/Logs/com.jitouch.Jitouch.stderr</string>
	<key>StandardOutPath</key>
	<string>/Users/USERNAME/Library/Logs/com.jitouch.Jitouch.stdout</string>
	<key>Umask</key>
	<integer>63</integer>
</dict>
</plist>
```
- change `USERNAME` to your username and `/PATH/TO` to either `/` or `/Users/USERNAME`, depending on where Jitouch.prefPane is installed.
- turn off Jitouch in System Preferences
- enable the LaunchAgent with `launchctl load -w ~/Library/LaunchAgents/com.jitouch.Jitouch.plist`.

(To remove the LaunchAgent, use `launchctl unload -w ~/Library/LaunchAgents/com.jitouch.Jitouch.plist`, remove `~/Library/LaunchAgents/com.jitouch.Jitouch.plist`, and turn on Jitouch in System Preferences.)

Jitouch should start working and you should see log messages in `~/Library/Logs/com.jitouch.Jitouch.stderr`. I think the LaunchAgent will improve reliability as well.

**Comment by smilingpoplar** [comment]
Ok, I'll try LaunchAgent

Aaron Kollasch ***@***.***>于2021年11月29日 周一15:21写道：

**Comment by smilingpoplar** [comment]
It can't start

2021-11-29 16:11:27.751 Jitouch[41869:1320202] Initializing.
2021-11-29 16:11:27.752 Jitouch[41869:1320202] start device 0 144115188075855919 family 108 not running

> I've encountered this problem too. After a longer sleep I still have to manually start Jitouch. I think the fix will be using a LaunchAgent to run Jitouch instead of enabling it as a startup item, but I haven't gotten to it yet.
> 
> Jitouch doesn't output logs to a file, but LaunchAgents can, so in the meantime, you can try running Jitouch as a LaunchAgent with these steps:
> 
> * create `~/Library/LaunchAgents/com.jitouch.Jitouch.plist`
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>KeepAlive</key>
> 	<true/>
> 	<key>Label</key>
> 	<string>Jitouch</string>
> 	<key>ProcessType</key>
> 	<string>Interactive</string>
> 	<key>Program</key>
> 	<string>/PATH/TO/Library/PreferencePanes/Jitouch.prefPane/Contents/Resources/Jitouch.app/Contents/MacOS/Jitouch</string>
> 	<key>RunAtLoad</key>
> 	<true/>
> 	<key>StandardErrorPath</key>
> 	<string>/Users/USERNAME/Library/Logs/com.jitouch.Jitouch.stderr</string>
> 	<key>StandardOutPath</key>
> 	<string>/Users/USERNAME/Library/Logs/com.jitouch.Jitouch.stdout</string>
> 	<key>Umask</key>
> 	<integer>63</integer>
> </dict>
> </plist>
> ```
> 
> * change `USERNAME` to your username and `/PATH/TO` to either `/` or `/Users/USERNAME`, depending on where Jitouch.prefPane is installed.
> * turn off Jitouch in System Preferences
> * enable the LaunchAgent with `launchctl load -w ~/Library/LaunchAgents/com.jitouch.Jitouch.plist`.
> 
> (To remove the LaunchAgent, use `launchctl unload -w ~/Library/LaunchAgents/com.jitouch.Jitouch.plist`, remove `~/Library/LaunchAgents/com.jitouch.Jitouch.plist`, and turn on Jitouch in System Preferences.)
> 
> Jitouch should start working and you should see log messages in `~/Library/Logs/com.jitouch.Jitouch.stderr`. I think the LaunchAgent will improve reliability as well.

**Comment by aaronkollasch** [comment]
Those logs are normal, the "not running" refers to the state before the device is started, and I haven't added a log message after starting yet. I see the same messages, including `*** Recognized ...` when run in a terminal but not a LaunchAgent, and the LaunchAgent works fine.

Does Jitouch respond to gestures when you run it inside a LaunchAgent?

**Comment by smilingpoplar** [comment]
no, not respond to gesture, either start from LaunchAgent or shell

Aaron Kollasch ***@***.***>于2021年11月29日 周一21:58写道：

**Comment by smilingpoplar** [comment]
Oh, I see jitouch icon in status bar. Should I click on it -> Open Preferences -> turn it on?

**Comment by aaronkollasch** [comment]
Ah yeah, that's my mistake in the directions then - I'll correct them for anyone trying this.

**Comment by aaronkollasch** [comment]
I'm glad to hear the LaunchAgent is working. Let me know if that solves or doesn't solve your problem.

**Comment by smilingpoplar** [comment]
After wakeup, jitouch closes two tab in one close gesture. 

`ps aux | grep Jitouch` shows two instances of /Library/PreferencePanes/Jitouch.prefPane/Contents/Resources/Jitouch.app/Contents/MacOS/Jitouch

> I'm glad to hear the LaunchAgent is working. Let me know if that solves or doesn't solve your problem.

**Comment by aaronkollasch** [comment]
Did you by chance have Jitouch.prefPane open in System Preferences when waking up? Or is Jitouch in your Login Items?

**Comment by smilingpoplar** [comment]
no login items.

About Jitouch.prefPane, I'm confused. Should I manually turn on jitouch in
prefPane after LauchAgent start jitouch? Yes, I manually turn it on, or
LauchAgent alone doesn't work.

I'll let you know if this scene happens again.

Aaron Kollasch ***@***.***>于2021年11月30日 周二06:28写道：

**Comment by aaronkollasch** [comment]
Leave it on. I mentioned the preformed because in `JitouchPref.m` `mainViewDidLoad` there is a command that starts Jitouch, which could lead to two instances running at the same time. It should only activate when you open the prefpane or if System Preferences is open to the prefpane when the system wakes up, I think. I'll remove the command when I get a LaunchAgent build working.

**Comment by aaronkollasch** [comment]
@smilingpoplar [Jitouch v2.78](https://github.com/aaronkollasch/jitouch/releases/tag/v2.78) is now up with built-in LaunchAgent support.

**Comment by smilingpoplar** [comment]
great

Aaron Kollasch ***@***.***>于2021年12月5日 周日06:25写道：

**Pull request merged**
